import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  appBarContent: {
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    maxWidth: 1280,
    width: '100%',
    alignSelf: 'center',
  },
  appBarTitle: {
    fontFamily: 'Inter',
    fontSize: 20,
    fontWeight: '700',
  },
  iconButton: {
    padding: 8,
    borderRadius: 999,
  },
  mainContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    maxWidth: 1280,
    alignSelf: 'center',
    width: '100%',
  },
  headerSection: {
    marginBottom: 16,
    gap: 4,
  },
  pageTitle: {
    fontFamily: 'Inter',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 26,
    letterSpacing: -0.2,
  },
  pageTitleLarge: {
    fontFamily: 'Inter',
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 34,
    letterSpacing: -0.4,
  },
  pageSubtitle: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 18,
  },
  formBlock: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    gap: 14,
    marginTop: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  cardHeader: {
    marginBottom: 12,
    gap: 4,
    zIndex: 10,
  },
  title: {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  subtitle: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 18,
  },
  clipboardBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 10,
    zIndex: 10,
  },
  clipboardText: {
    fontSize: 13,
    flex: 1,
  },
  clipboardCode: {
    fontWeight: '700',
    fontFamily: 'Courier Prime',
    fontSize: 13,
  },
  emailSyncCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    zIndex: 10,
  },
  emailSyncTextWrapper: {
    flex: 1,
  },
  emailSyncTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  emailSyncSubtitle: {
    fontSize: 12,
    marginTop: 2,
  },
  form: {
    gap: 14,
    zIndex: 10,
  },
  inputGroup: {
    gap: 6,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inputLabel: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  requiredAsterisk: {},
  optionalText: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '400',
  },
  inputWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  inputIconLeft: {
    position: 'absolute',
    left: 12,
    zIndex: 10,
  },
  input: {
    fontFamily: 'Inter',
    fontSize: 14,
    borderWidth: 1,
    borderRadius: 10,
    height: 46,
    paddingLeft: 40,
    paddingRight: 14,
  },
  inputMono: {
    fontFamily: 'Courier Prime',
    fontSize: 14,
    borderWidth: 1,
    borderRadius: 10,
    height: 46,
    paddingLeft: 40,
    paddingRight: 44,
  },
  qrButton: {
    position: 'absolute',
    right: 6,
    zIndex: 10,
    padding: 6,
    borderRadius: 999,
  },
  submitContainer: {
    paddingTop: 8,
  },
  submitButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderRadius: 10,
    height: 46,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  submitButtonText: {
    fontFamily: 'Inter',
    fontSize: 15,
    fontWeight: '600',
  },
  carrierSelectorBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    height: 46,
  },
  carrierSelectorContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  carrierSelectorText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
  },
  carrierSelectorPlaceholder: {
    fontFamily: 'Inter',
    fontSize: 14,
  },
});
