import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  appBar: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(197, 197, 211, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
    zIndex: 50,
  },
  appBarContent: {
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    maxWidth: 1280,
    width: '100%',
    alignSelf: 'center',
  },
  appBarTitle: {
    fontFamily: 'Inter',
    fontSize: 20,
    fontWeight: '700',
  },
  iconButton: {
    padding: 8,
    borderRadius: 999,
  },
  mainContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    maxWidth: 896,
    alignSelf: 'center',
    width: '100%',
    gap: 16,
  },
  summaryHeader: {
    flexDirection: 'column',
    borderWidth: 1,
    padding: 12,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  summaryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
  },
  summaryCarrierCol: {
    flex: 1,
    marginRight: 12,
  },
  summarySectionLabel: {
    fontFamily: 'Inter',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  summaryCarrierInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  carrierNameText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '700',
  },
  summaryStatusCol: {
    alignItems: 'flex-end',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  statusBadgeText: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  summaryDivider: {
    height: 1,
    width: '100%',
    marginVertical: 10,
  },
  summaryBottomContent: {
    width: '100%',
    gap: 4,
  },
  summaryTitle: {
    fontFamily: 'Inter',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  trackingNumberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  trackingNumberLabel: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  trackingLabel: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  trackingNumber: {
    fontFamily: 'Courier Prime',
    fontSize: 15,
    fontWeight: '700',
  },
  gridContainer: {
    flexDirection: 'column',
    gap: 12,
  },
  gridContainerDesktop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  detailsSection: {
    flexDirection: 'column',
    gap: 12,
  },
  detailsColDesktop: {
    flex: 1,
  },
  timelineColDesktop: {
    flex: 2,
  },
  card: {
    borderWidth: 1,
    padding: 14,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  timelineCard: {
    flex: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  cardTitle: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600',
  },
  infoGroup: {
    marginVertical: 2,
  },
  infoLabel: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  infoValuePrimary: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
  },
  infoValue: {
    fontFamily: 'Inter',
    fontSize: 14,
  },
  infoValueSmall: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 18,
  },
  divider: {
    height: 1,
    marginVertical: 8,
  },
  timelineContainer: {
    paddingLeft: 8,
    position: 'relative',
    marginTop: 4,
  },
  timelineStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 16,
  },
  timelineDotActiveWrapper: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#fea619',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#ffffff',
    marginTop: 2,
  },
  timelineDotActiveInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#855300',
  },
  timelineDotCompleted: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#004a31',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#ffffff',
    marginTop: 2,
  },
  timelineContent: {
    flex: 1,
  },
  timelineTitleActive: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '700',
  },
  timelineTitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
  },
  timelineDescription: {
    fontFamily: 'Inter',
    fontSize: 12,
    marginTop: 2,
  },
  timelineTime: {
    fontFamily: 'Courier Prime',
    fontSize: 11,
    marginTop: 2,
  },
});
